### ISSUE TITLE
Evolucionando APIs con GraphQL

### ISSUE THREAD

**Issue by AlexNima** [lima-js/limajs.org#104]
GraphQL no es solo una buena manera de seleccionar data de tu servidor si no también un formato expresivo para describir tu modelo de datos.

**Comment by JoshDev1205** [comment]
Super Nice :smile: :+1:

**Comment by lupomontero** [comment]
Hola @AlexNima, solo para aclarar, este _issue_ representa una propuesta de charla? :see_no_evil:

**Comment by AlexNima** [comment]
> Hola @AlexNima, solo para aclarar, este _issue_ representa una propuesta de charla? 🙈

Hola, es correcto.

**Comment by JoshDev1205** [comment]
Te animas a crearlo con la plantilla para asi tenerlo con el mismo formato y seria genial en el titulo ponerlo para un mes en referencia en el que quieras participar como speaker ? :smile:

**Comment by lizzie136** [comment]
Hola @AlexNima estas disponible el 20 de febrero para dar esta charla?

**Comment by AlexNima** [comment]
Hola @lizzie136, si estoy disponible el 20 de febrero para dar esta charla. Nos ponemos en contacto?

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que esta charla ya se dio en el [meetup de febrero](https://www.meetup.com/LimaJS/events/kmwfjrybcdbbc/). Gracias @AlexNima :raised_hands:
