### ISSUE TITLE
Microservicios: Principios y mitos

### ISSUE THREAD

**Issue by jersson** [lima-js/limajs.org#105]
## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [X] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jersson Dongo

## Cuéntanos un poco sobre ti
Soy un profesional en TI, arquitecto de corazón con mucho interés en la investigación y puesta en práctica de nuevas tecnologías. Busco equilibrar mi pasión tecnológica por medio de la lectura, escritura y viajes :)

## ¿Cuál es el título de tu charla?
Microservicios:
Principios y mitos.

## Danos una descripción de tu charla (20 palabras)
Experiencias sobre implementación de microservicios y cómo es que se están concibiendo en el entorno local. Para ello es importante compartir algunos principios y mitos con los que me he encontrado.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: [@jersson](https://twitter.com/Jersson)

## ¿Representas a alguna compañía o empresa?
No

## ¿Quieres agregar algo más?
No lo sé aún, quedo atento. Gracias!

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Genial! Gracias por mandar tu charla 🎉 
Nos gusta tu charla para enero. Te contacto por interno :)

**Comment by jersson** [comment]
Gracias!

**Comment by lizzie136** [comment]
Gracias @jersson por tu charla!
