### ISSUE TITLE
Construyendo una extension de chrome para obtener immunidad al coronavirus

### ISSUE THREAD

**Issue by brunogonzales** [lima-js/limajs.org#106]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Bruno Gonzales

## Cuéntanos un poco sobre ti
Trabajo actualmente como full stack developer en Get on Board. Me encanta enseñar y jugar con mi gata Andrómeda.

## ¿Cuál es el título de tu charla?
Building a Coronavirus Immunity Chrome extension

## Danos una descripción de tu charla (20 palabras)
Construiremos una simple extension de chrome que oculta cualquier nodo de texto que contenga la palabra coronavirus. 

## ¿Tienes alguna red social donde podamos contactarte?
[Twitter](https://twitter.com/sugartayta)
[Email](brunogonzales1129@gmail.com)

## ¿Representas a alguna compañía o empresa?
No

## ¿Quieres agregar algo más?

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
nos vemos el lunes en tu dry run :D

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este _issue_ ya que esta charla ya se dio en el [meetup de febrero](https://www.meetup.com/LimaJS/events/kmwfjrybcdbbc/). Gracias @brunogonzales :raised_hands:
