### ISSUE TITLE
Prisma2: OMR (?) + Migration Engine

### ISSUE THREAD

**Issue by kranfix** [lima-js/limajs.org#107]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Frank A. Moreno Vera (@kranfix)

## Cuéntanos un poco sobre ti
Desde mi primer hola mundo a las 7 años, dedico mucho tiempo en investigar las más innovadoras tecnologías. Pese a ser un abanderado del software, estudié Ing. Electrónica en la UNI para satisfacer mi apetito de conocimiento en física, matemáticas y hardware, trabajando en proyectos de robótica, computer vision, desktop dashboard apps, web (backend y frontend), etc. Durante años me he dedicado a hacer proyectos de IoT (combinando todos las disciplinas que me mencioné). Actualmente, soy uno de los líderes de la comunidad de @flutterperu y promuevo las tecnologías que tenemos que manejar para poder competir con software internacional y, así, acortar nuestra brecha tecnológica.

## ¿Cuál es el título de tu charla?
Prisma2: OMR (?) + Migration Engine

## Danos una descripción de tu charla (20 palabras)
Prisma2 es un framework que nos  permite definir modelos de datos en DB y hacer migraciones de dichos modelos, a la par de que auto-genera código para Node.js con TypeScript, la cual podemos usar para hacer backend services.

## ¿Tienes alguna red social donde podamos contactarte?

twitter.com/kranfix
github.com/kranfix
linkedin.com/in/kranfix
facebook.com/kranfix

## ¿Representas a alguna compañía o empresa?

Voy por mi cuenta.

## ¿Quieres agregar algo más?

Mi charla puede ser mejor si dura 45 minutos. Agradecería que me confirmen si es posible la extensión del tiempo.

**Comment by lupomontero** [comment]
Hola @kranfix, gracias por la propuesta de charla :+1: 

Se ve súper interesante. Me imagino que en el futuro próximo estaremos haciendo los meetups en línea... [esta semana (mañana) tenemos meetup](https://www.meetup.com/LimaJS/events/kmwfjrybcfbzb/), y como es marzo este meetup tendremos 3 ponentes mujeres.

Esta propuesta queda abierta a consideración para futuros meetups :wink: 

cc/ @lizzie136 @wixo @Xpktro

**Comment by lizzie136** [comment]
Hola @kranfix ! Por que medio podría contactarte para organizar detalles? Estas en el slack de Lima JS?

**Comment by kranfix** [comment]
Hola @lizzie136. No estoy en el slack, pero puedes hablarme por mi fb que lo dejé en mi descripción.

**Comment by lizzie136** [comment]
Oki @kranfix Te acabo de escribir por fb :)
