### ISSUE TITLE
Verifiable Credentials Data Model 1.0 (Usando Blockchain)

### ISSUE THREAD

**Issue by lacchain-stamping** [lima-js/limajs.org#108]
Una credencial verificable contiene al menos la información que se encuentra en una credencial física (Diploma, Documento o Certificado); pero haciendo uso de las firmas digitales, permite que puedan ser verificadas, resistentes a la manipulación y más confiables que las credenciales físicas.
Ha sido Recomendado por la W3 en Nov. del 2019 para expresar información por la web.

Agenda:
Introducción a las credenciales
Actores
Como funcionan
Casos de Usos

**Comment by lizzie136** [comment]
Hola @lacchain-stamping ! Gracias por tu propuesta de charla.
Podrías responder las siguientes preguntas?
- Cuál es tu nombre?
- Cuéntanos un poco sobre ti
- ¿Tienes alguna red social donde podamos contactarte?
- ¿Representas a alguna compañía o empresa?
- Tendrías disponibilidad este domingo o el siguiente?

**Comment by lupomontero** [comment]
Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN
