### ISSUE TITLE
La revolución de Deno

### ISSUE THREAD

**Issue by edgargs** [lima-js/limajs.org#110]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Edgar Rios Navarro

## Cuéntanos un poco sobre ti
Entusiasta de la programación y nuevas tecnologías.

## ¿Cuál es el título de tu charla?

La revolución de Deno

## Danos una descripción de tu charla (20 palabras)

Presentación a la comunidad sobre Deno y los cambios/diferencias respecto a NodeJS.

## ¿Tienes alguna red social donde podamos contactarte?

https://twitter.com/e240683

## ¿Representas a alguna compañía o empresa?
Personal

## ¿Quieres agregar algo más?

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Hola @edgargs, ha pasado ya 1 año desde tu propuesta... :see_no_evil: ... Este último año ha sido bien difícil para todos y recién nos estamos volviendo a poner las pilas con los meetups (aunque claro, por ahora siempre en formato remoto).

¿Te animarías todavía a presentar esta charla en algún meetup? La semana que viene tenemos [meetup](https://www.meetup.com/LimaJS/events/kwbkfsyccjbwb/) y el mes que viene deberíamos volver a tener otro.
