### ISSUE TITLE
La nueva normalidad

### ISSUE THREAD

**Issue by zentaker** [lima-js/limajs.org#115]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [0] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Alejandro Palomino wong 

## Cuéntanos un poco sobre ti
Desarrollador con experiencia en la transformación digital, creando experiencias centradas en el usuario. 

## ¿Cuál es el título de tu charla?
Como el concepto de progreso ha desbloqueado el conocimiento y el crecimiento exponencial.

## Danos una descripción de tu charla (20 palabras)

La evolución de la anatomía humana se detuvo hace 200,000 años dejando consigo la evolución social y cultural, trayendo consigo la evolución del conocimiento y la mejora del bienestar. Se generó mediante el progreso tecnológico a través del desbloqueo en el conocimiento colectivo.

## ¿Tienes alguna red social donde podamos contactarte?
alejandropalomino.pe

## ¿Representas a alguna compañía o empresa?
No 
## ¿Quieres agregar algo más?

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento presencial para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN
