### ISSUE TITLE
What the Hell is Prisma ?

### ISSUE THREAD

**Issue by JoshDev1205** [lima-js/limajs.org#116]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Josh Ospina Tafur
## Cuéntanos un poco sobre ti
Nerd, Vue Lover, Prisma Ambassador

## ¿Cuál es el título de tu charla?
What the Hell is Prisma ?

## Danos una descripción de tu charla (20 palabras)
Hablaremos de Prisma desde la V1 hasta la V2 que ha revolucionado muchos aspectos del Backend

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/Josh_Dev1205

## ¿Representas a alguna compañía o empresa?
Visma Latam

## ¿Quieres agregar algo más?
Extrañaba las meetups :)

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Buenazo @JoshDev1205 :+1: 

En principio esta charla estaría haciéndose en el [meetup de julio](https://www.meetup.com/LimaJS/events/kwbkfsycckbtb/).

**Comment by JoshDev1205** [comment]
Buenos dias,
Podriamos retomar esta charla para noviembre ??
saludos

**Comment by lupomontero** [comment]
Será que hacemos meetup este mes? ... quién se anima? @lizzie136?

**Comment by lupomontero** [comment]
Hola @JoshDev1205 ... han pasado años... qué es de tu vida?

Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento presencial para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN

**Comment by JoshDev1205** [comment]
Buenas tardes @lupomontero que gusto saber que se va a resucitar limajs encantado de poder proponer una charla y compartir cuenta conmigo
