### ISSUE TITLE
Microfrontend architecture

### ISSUE THREAD

**Issue by ldiego73** [lima-js/limajs.org#118]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Luis Diego

## Cuéntanos un poco sobre ti
Engineer Manager con experiencia liderando equipos de la Plataforma Core y el uso de tecnologías disruptivas.

## ¿Cuál es el título de tu charla?
Microfrontend architecture

## Danos una descripción de tu charla (20 palabras)
Una breve explicación de como se debe realizar una arquitectura para proyectos react y react-native 

## ¿Tienes alguna red social donde podamos contactarte?
https://www.instagram.com/ldiego73
https://www.linkedin.com/in/ldiego73
https://twitter.com/ldiego73

## ¿Representas a alguna compañía o empresa?
Auna

## ¿Quieres agregar algo más?
Se compartirá una demo breve de la implementación
---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Hola Luis Diego @ldiego73  ,
¿aún estas interesado en dar una esta charla? ¿Tienes disponible el 15 de Septiembre?

Te escribo por twitter también.

**Comment by lupomontero** [comment]
Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento presencial para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN

**Comment by ldiego73** [comment]
Hola Lupo qué tal, muchas gracias por el mensaje. Para esas fechas estaré en Lima. 

Puedo retomar esta charla, voy abriendo un Issue más rato.
