### ISSUE TITLE
Construyendo React desde 0 | Cómo funciona React realmente?

### ISSUE THREAD

**Issue by diegotc86** [lima-js/limajs.org#120]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Diego Torres

## Cuéntanos un poco sobre ti
Actualmente soy lider educativo en Codeable (escuela de programación full-stack). Si bien estudié ing. de sistemas, descubrí el gusto por la programación recien en 2018. Desde entonces ha sido una aventura de mucho aprendizaje y crecimiento. Disfruto compartir lo aprendido y entender a profundidad cómo funcionan las cosas.

## ¿Cuál es el título de tu charla?
Construyendo React desde 0 | Cómo funciona React realmente?

## Danos una descripción de tu charla (20 palabras)
Descubre cómo funciona React construyendo desde 0 las principales funcionalidades como `render`, `useState` y `useEffect`

## ¿Tienes alguna red social donde podamos contactarte?
https://www.linkedin.com/in/diegotc86/

## ¿Representas a alguna compañía o empresa?
Si, Codeable.

## ¿Quieres agregar algo más?
Todo bien, gracias por la oportunidad.
---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento presencial para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN
