### ISSUE TITLE
Criptografía de llave pública con Javascript (orientado al Blockchain)

### ISSUE THREAD

**Issue by leemarreros** [lima-js/limajs.org#121]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Lee Marreros

## Cuéntanos un poco sobre ti
Desarrollador de Blockchain. Fundador de la escuela Blockchain Bites. Conferencista, escritor y profesor en tópicos de Blockchain. 5+ años de experiencia en compañías Fintech & Blockchain (e.g. Yodlee, Tenpo, FIDIS, CuyToken, Pachacuy, Rand Network, dcSpark). Estudié Computer Programming Certificate en la Universidad de Santa Clara, California, USA. Graduado del bootcamp del programa inmersivo de Ingeniería de Software Hack Reactor, Los Ángeles. Graduado de Lean UX and Service Design Program (UTEC) y del diplomado de Finanzas Corporativas (UPC)

## ¿Cuál es el título de tu charla?

Fundamentos de criptografía de llave pública con Javascript (orientado al Blockchain)

## Danos una descripción de tu charla (20 palabras)

Aprenderemos sobre el uso de la criptografía de llave pública para conocer cómo se usan en el Blockchainpara enviar mensajes secretos y garantizar la fuente

## ¿Tienes alguna red social donde podamos contactarte?

[LinkedIn](https://linkedin.com/in/lee-marreros)

[Twitter](https://twitter.com/LeeMarreros)

## ¿Representas a alguna compañía o empresa?

Blockchain Bites

## ¿Quieres agregar algo más?

Me gustaría presentar la ponencia en un día del 19 al 30 de Junio

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Después de unos años de inactividad, estamos tratando de resucitar la comunidad y estamos planeando un evento presencial para diciembre. No sé si seguirás en Lima, pero si es así quizás te animes a abrir un issue nuevo con una nueva propuesta de charla.

Aprovecho también a comentar que hemos mudado el chat de la comunidad de Slack a Discord:
https://discord.gg/AZktPrehGN
