### ISSUE TITLE
Integración de Nuxt.js con Sanity CMS

### ISSUE THREAD

**Issue by vr1eva** [lima-js/limajs.org#125]
### ¿Qué tipo de presentación quieres hacer?

Keynote (20 a 30 minutos)

### ¿Cuál es tu nombre?

Bruno Gonzales

### Cuéntanos un poco sobre ti

Soy un miembro de la comunidad con conocimientos en React y Vue. 

### ¿Cuál es el título de tu charla?

Nuxt Insanity: Integración con un CMS

### Danos una descripción de tu charla (20 palabras)

En esta charla mostraré rápidamente cómo integrar Nuxt.js con Sanity en simples pasos para crear sitios dinámicos con contenido gestionado.

### ¿Tienes alguna red social donde podamos contactarte?

Pueden encontrarme en el servidor de Discord de lima-js como vr1.

### ¿Representas a alguna compañía o empresa?

No.

### ¿Quieres agregar algo más?

Estoy muy emocionado porque tendré la oportunidad de compartir cómo integrar estas dos poderosas herramientas para crear una solución que se está volviendo cada vez más relevante en el desarrollo web.

**Comment by lupomontero** [comment]
Buenazo @vr1eva :raised_hands: 

Te animarías a hacerla para el meetup de noviembre (jueves 21)?

**Comment by vr1eva** [comment]
@lupomontero si, con mucho gusto. Gracias

**Comment by lupomontero** [comment]
Esta charla ya está [programada para este jueves](https://www.meetup.com/limajs/events/304433696/) :tada: ... así que me tomo la libertad de ir cerrando este issue.
