### ISSUE TITLE
WebSockets en Acción: Creación de un servidor y cliente con React feat. Socket.IO

### ISSUE THREAD

**Issue by vr1eva** [lima-js/limajs.org#126]
### ¿Qué tipo de presentación quieres hacer?

Keynote (20 a 30 minutos)

### ¿Cuál es tu nombre?

Bruno Gonzales

### Cuéntanos un poco sobre ti

Soy un miembro de la comunidad con conocimientos en Next.js y Nuxt.

### ¿Cuál es el título de tu charla?

WebSockets en Acción: Creación de un servidor y cliente con React y Socket.IO

### Danos una descripción de tu charla (20 palabras)

Exploraremos cómo crear un servidor WebSocket con Node.js y Socket.IO, y un cliente interactivo utilizando React para comunicación en tiempo real.
![image](https://github.com/user-attachments/assets/dfbaa450-967a-4a85-9f2c-57527ab89ea3)

### ¿Tienes alguna red social donde podamos contactarte?

Pueden encontrarme en el servidor de Discord de lima-js como vr1, o enviarme un mensaje a través de mi perfil en BlueSky: [vr1eva.bsky.social](https://bsky.app/profile/vr1eva.bsky.social).

### ¿Representas a alguna compañía o empresa?

No.

### ¿Quieres agregar algo más?

Estoy emocionado de compartir cómo estas tecnologías permiten implementar funciones en tiempo real, ideales para chat, notificaciones y dashboards interactivas.

**Comment by lupomontero** [comment]
Gracias por la propuesta @vr1eva 🙌

Vamos a esperar unos días a ver si recibimos más propuestas para el meetup de diciembre antes de tomar una decisión... 🤞

**Comment by lupomontero** [comment]
Queda agendada para el meetup de mañana! [www.meetup.com/limajs/events/304179185/](http://www.meetup.com/limajs/events/304179185/)
