### ISSUE TITLE
Potenciando Node.js: El poder de C++ al alcance

### ISSUE THREAD

**Issue by andresdiaz29** [lima-js/limajs.org#128]
### ¿Qué tipo de presentación quieres hacer?

Keynote (20 a 30 minutos)

### ¿Cuál es tu nombre?

Andres Eduardo Diaz Ortiz

### Cuéntanos un poco sobre ti

Venezolano en Lima, Perú, desarrollador JavaScript, Angular y NodeJs, cuya meta es continuar profundizando en el universo de JS.

### ¿Cuál es el título de tu charla?

Potenciando Node.js: El poder de C++ al alcance

### Danos una descripción de tu charla (20 palabras)

¿No conoces de C++? ¡Descuida! Vamos a conocer como potenciar nuestros servicios NodeJs, utilizando un enfoque Non blocking, donde C++ es el invitado.

### ¿Tienes alguna red social donde podamos contactarte?

https://www.linkedin.com/in/andresdiazortiz/

### ¿Representas a alguna compañía o empresa?

No

### ¿Quieres agregar algo más?

En este espacio, quiero presentar una charla que hice recientemente a otro grupo, y que me gustaría escuchar diferentes experiencias relacionadas a NodeJs relacionadas a performance

**Comment by lupomontero** [comment]
Hola @andresdiaz29, gracias por la propuesta y disculpa por la demora en contestar. ¿Te animas a presentar en el meetup de mañana? Finalmente será de 6 a 8pm.

**Comment by vagostep** [comment]
Cuenten conmigo!

**Comment by lupomontero** [comment]
Excelente 💫

**Comment by lupomontero** [comment]
Queda agendada para el meetup de mañana! www.meetup.com/limajs/events/304179185/
