### ISSUE TITLE
Patrocinadores (Sponsors)

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#14]
Qué les parecería introducir el concepto de patrocinadores (sponsors) dentro del grupo? Hasta ahora los sponsors han sido tradicionalmente las organizaciones que han facilitado el espacio. Mi propuesta es hacer estos patrocinios un poco más oficiales y abrir la posibilidad a que se patrocinen otras cosas como stickers, comida/bebida en los eventos, pagar algunos recursos como dominio, quizás una cuenta de meetup.com, ... 🤔 

Para poder aterrizar esto propongo lo siguiente:

1. Que se lleven las cuentas de forma abierta en un archivo plano en GitHub.
2. Que solo se hagan gastos propuestos de forma abierta y aprobados de forma unánime por los organizadores que estén a cargo en ese momento (mínimo 4, tendríamos que decidir quienes son esas personas y adoptar algún proceso para hacer esos roles oficiales).
3. Tener un espacio en el [website](https://limajs.org/) donde mencionemos a los sponsors

Qué opinan? Qué se les ocurre? Conocen alguna referencia de otros grupos que manejen sponsors?

cc/ @wixo @lizzie136 @PuercoPop @Xpktro

**Comment by wixo** [comment]
Hola, estoy a favor de tener patrocinadores para otros costos, especialmente comida y servidores.
Lo que me parece podríamos hacer es definir un monto para que se pueda compartir con los posibles patrocinadores.

Por ejemplo, para la comida podemos tener un presupuesto fijo que garantiza comida y bebida para 30 personas (número tentativo) que saldría de una compra por delivery (ejemplo: https://www.plazavea.com.pe/gaseosa-coca-cola-botella-300ml-paquete-6un/p).

Esto haría más fácil la comunicación con un futuro sponsor ya que quedaría claro cuanto debería de ser su aporte y cual es el beneficio para la comunidad.

Si les parece la idea podemos decidir un paquete y publicar el costo total. La que me parece tiene una mejor idea sobre costos es @lizzie136 ya que ella últimamente nos estuvo patrocinando comida y bebida 😄

Sobre los puntos compartidos:

1) De acuerdo con las cuentas públicas, no se si un archivo plano.
2) Creo q mi propuesta elimina la necesidad de manejar una caja chica, si hay patrocinio entonces hay beneficios, y se vería de mes a mes.
3) Claro, una mención en la reunión en sí, una oportunidad de hablar unos 5 minutos y una mención en el sitio web por el mes.

Igual para el costo de servidores.

**Comment by lupomontero** [comment]
Por ahora, creo que el único gasto fijo que hay es el nombre de dominio ([limajs.org](http://limajs.org/)), que lo tengo registrado en mi cuenta de [AWS](https://aws.amazon.com/) y sale a $12/año (toca renovarlo el 13 de diciembre). Por otro lado, DNS está manejado con una cuenta gratuita en [CloudFlare](https://www.cloudflare.com/), y el hosting con [GitHub pages](https://pages.github.com/) (también gratis).

A mí me encantaría que tengamos cuenta en [Meetup.com](https://www.meetup.com/) ($5/mes) para darle un poco más de visibilidad al grupo.

A esto habría que sumarle los gastos de bebida/comida y stickers, que por ahora parece que ha cubierto @lizzie136. Podrían echar una mano con los detalles?

En ánimo de ser inclusivxs, también me gustaría pedir que se tuviera en cuenta, fruta :green_apple:, jugos :tropical_drink: y otras opciones vegetarianas :tomato: para evitar caer en solo gaseosa y pizza :pizza:.

***

PS: Por otro lado, como referencia, también tengo registrados los dominios jsconf.pe y javascript.pe (que actualmente redireccionan a limajs.org). Qué opinan si los incluimos en el presupuesto?

**Comment by lizzie136** [comment]
Hola, de las cosas que he cubierto, no recuerdo haber puesto pizza especificamente, pero si cosas más sencillas: 
En las reus más "grades" (30 y algo) personas (entre 50 y 60 soles): 
 - Dos porciones de [Galletas Dulces (orejitas)](https://www.vivanda.com.pe/la-florencia-orejitas-cj-x-250g/p)
 - Dos porciones de [Pretzels](https://www.vivanda.com.pe/piqueo-snyder-of-hanover-pretzels-palitos-crocantes-bolsa-255gr/p)
 - Gaseosas 2. [Por ejemplo Inka Kola](https://www.vivanda.com.pe/gaseosa-inca-kola-botella-3l/p)
En medianas o pequeñas:
Ejemplo 1 (25):
- [Chocoton similar](https://www.vivanda.com.pe/paneton-blanca-flor-chocolate-caja-500g/p),compre dos, pero al final comimos uno y algo más
- Gaseosas
Ejemplo 2 (21): 
- Un par de[ kekes envasados ](https://www.vivanda.com.pe/keke-bimbo-sabor-naranja-bolsa-400gr/p)
- Gasesosas.

Saco la cuenta un poco por conversión de 20 - 30 % de los registrados de eventbrite.

Por otro lado, me parece interesante la idea de tener sponsor, pero sería interesante poder independizarlo de alguna manera. Puede ser que la misma gente se organize en traer algo? Ponerlo en slack por si hay algún voluntario? Tampoco quiero incomodarlos y hacerlos sentir que es una obligación o que es necesario. 

Empecé a hacerlo más porque las personas en su mayoría vienen de trabajar o estudiar todo el día, y en el tráfico, entonces van a estar más cansado y/o desorientados si no pudieron recargar energías. La idea es que tampoco sea algo muy pesado como pizza que luego te da ganas de dormir. Fruta puede ser, implica un poco de logística en lavarlas, y mantenerlas si quedan. De repente frutos secos también? Si tenemos un pequeño prespuesto, podría comprarse en cantidad y son mas sencillas de guardar.

**Comment by lupomontero** [comment]
Gracias por el detalle @lizzie136.

Les parece si tratamos de concretar un paquete para la reu de este mes (el 23 de agosto) y de ahí ofrecemos a la comunidad y sponsors potenciales la posibilidad de contribuir a cubrir el gasto?

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que está un poco desactualizado y ya tenemos un [texto para sponsors](https://github.com/lima-js/limajs.org/blob/master/SPONSORS.md) en el repo :wink:
