### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#15]
Sería buenazo hacer un buen batch de stickers, en varios tamaños y quizás hasta un _banner_ que podamos usar en los meetups (y otras cosas... abierto a propuestas).

Esto está relacionado a https://github.com/lima-js/limajs.org/issues/14.

cc/ @lizzie136 @wixo

**Comment by lizzie136** [comment]
Aún tengo del primer batch de abril/mayo. - - Qué otros tamaños formas se puede hacer? 
- Qué les parece tener un concurso de diseños para cada quarter/mes o año?

**Comment by lupomontero** [comment]
@lizzie136: me parece super buena idea hacer un concurso de diseños. Te animarías a organizar algo?

**Comment by lizzie136** [comment]
Hola @lupomontero, de hecho aún tengo la idea, pero mientras tanto, he encargado unos diseños temáticos para Julio (aunque ya pasó), Agosto, Setiembre, Octubre, Noviembre y Diciembre. Las personas que vayan esos meses tendrán los stickers limited edition de ese mes. En cuanto los tenga los diseños los pongo por aquí o en Slack para que me den su feedback. Todavía hay un batch de los primeros stickers que los tiene @wixo.

**Comment by lupomontero** [comment]
@lizzie136?

**Comment by lizzie136** [comment]
Hola! a tus preguntas: 
- Se lo encargué a Malu Romero, no sé si la recuerdas. 
- Considerando el histórico, estoy considerando entre 40 y 60 stickers, pero ahí si me gustaría tener los diseños antes de mandar a imprimir cualquiera. Un poco para que al contractor le salga a cuenta traerlos él mismo. Y para tenerlos con tiempo. Podríamos considerar derepente que el tema no sea el mes necesariamente. Pero ahí si me gustaría su opinión @lupomontero @wixo @Xpktro 
- Esa es una buena pregunta, las planchas de 400 stickers de LimaJS de 5x5 me salieron 70 soles.

**Comment by lupomontero** [comment]
> Se lo encargué a Malu Romero, no sé si la recuerdas.

Claro que sí :+1:. Tienes algún boceto que se pueda compartir? Para cuándo crees que podamos ver algo?

> Podríamos considerar derepente que el tema no sea el mes necesariamente. Pero ahí si me gustaría su opinión @lupomontero @wixo @Xpktro

La idea de tener un diseño de sticker para cada mes me gusta :smile: 

> [...] las planchas de 400 stickers de LimaJS de 5x5 me salieron 70 soles.

Se pueden imprimir diferentes diseños en la misma _plancha_? Por ejemplo, imaginemos que queremos 50 stickers para cada mes; podríamos imprimir 8 diseños en una sola plancha?

**Comment by lizzie136** [comment]
Hola @lupomontero, @Xpktro  y @wixo, quería darles un update de este tema.

Conversé con el proveedor de los stickers, y también hace pines, gorras, polos, tazas etc etc. Con algo de presupuesto podemos ponernos creativos 😄💡!  

Pedí un batch de pines con el logo básico como para probar, me gustaría que luego me den feedback de cómo quedaron (Solo para que se den una idea el presupuesto del 100to es de 55 sols). Estoy coordinando con @wixo para que se los entreguen en Lima. 

Sobre los diseño, Malu me hizo un primer aproach y la verdad que no quedé muy convencida, de repente porque lo dije muy abstracto.  
De hecho si tienen ideas sería super genial que me las den/pasen para canalizarlo con ella y queden cosas super geniales!!! Ya creo que para el meet Up de agosto nos quedamos cortos, pero en todo caso el de Setiembre. 
![39558110_225809924764077_3090966892098093056_n](https://user-images.githubusercontent.com/3421560/44495557-fa713200-a635-11e8-82a7-fdfb4c8a3d3a.jpg)

Un poco mi feedback fue un poco por los contrastes y que no agregan algún detalle específico. 

🌟  Si se animan a una propuesta también sería genial! Igual podemos abrirlo a concurso si les parece.

**Comment by lupomontero** [comment]
Cierro este issue por inactividad...
