### ISSUE TITLE
PPT Karaoke!

### ISSUE THREAD

**Issue by wixo** [lima-js/limajs.org#18]
Está idea me la estoy robando de un meetup en inglés donde los llaman Battledecks!

La dinámica es tener voluntari@s del público que salen a dar una charla sin saber las diapositivas.
Las diapositivas han sido preparadas de antemano con imágenes graciosas y sin sentido que solo se revelan en ese momento.

Voy a preparar 2 presentaciones de 10 diapositivas cada una para la próxima reunión, espero q hayan voluntari@s.
Estos Karaokes se pueden tener de intermedios entre las presentaciones.

**Comment by lupomontero** [comment]
:+1: 

BTW, qué les parece ir cerrando el jueves 23 de agosto para el meetup de este mes? En cuanto a _venue_, @Laboratoria está disponible, pero abierto a cualquier otra propuesta :smile: 

cc/ @lizzie136 @xpktro

**Comment by lizzie136** [comment]
@lupomontero Hola! Ya esta reservado para ese día en Laboratoria. Confirmado :v: 
Lo que faltan son los temas :) 
Una pregunta, cuánto tiempo de la agenda tomaría el Karaoke?

**Comment by lupomontero** [comment]
@wixo?

**Comment by wixo** [comment]
@lizzie136 los karaokes durarán 10 mins, seguro ponemos un timer para q los participantes sepan.

Me parece bien el 23 de agosto 👍

**Comment by lupomontero** [comment]
@wixo: te animas con un PR para actualizar [la agenda del próximo meetup](https://github.com/lima-js/limajs.org/blob/master/index.html#L52) con el PPT Karaoke?

**Comment by lizzie136** [comment]
Me parece que ya se agregó el PR de PPTKaraoke para este meetUp. Cerraríamos este issue luego del primer PPTKaraoke y con nuetros findings? @wixo @lupomontero @Xpktro? Luego del meet up me gustaría que agreguen qué tal les fue y si continueraríamos haciéndolo. Qué podemos mejorar con eso también.

**Comment by lupomontero** [comment]
EL PPTKaraoke aparece en el [evento en Eventbrite](https://www.eventbrite.com/e/limajs-agosto-tickets-49071586436), pero no ha habido pull request (así que no aparece en https://limajs.org/). @wixo, te animas con el PR? Si no avisa y me encargo yo.

Les parece si dejamos este _issue_ abierto para seguir la conversación con las conclusiones de la experiencia de este jueves?

**Comment by lupomontero** [comment]
Cierro este issue ya que los PPT Karaoke ya son una realidad... :rocket:
