### ISSUE TITLE
Recursos del grupo

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#20]
Hola todxs,

Abro este issue para transparentar un poco qué recursos existen del grupo y quienes administran dichos recursos. Agradecería si me pueden ayudar a completar este cuadro y actualizar admins según consideremos necesario.

| Servicio | Admins | Tipo de cuenta
| --- | --- | ---
| [GitHub](https://github.com/lima-js) | @lizzie136, @wixo, @lupomontero, @jpscaletti, @PuercoPop  | org
| [AWS](https://aws.amazon.com/): dominio ([limajs.org](https://limajs.org/)) | @lupomontero | usuario personal
| [Cloudflare](https://www.cloudflare.com/): DNS | @lupomontero | usuario personal
| [Twitter](https://twitter.com/js_peru) | @lizzie136, @lupomontero, ? | usuario compartido
| [Slack](https://limajs.slack.com/) | @wixo,  ? | ?
| [Eventbrite](https://www.eventbrite.com/o/limajs-7913150001) | @wixo, ? | ?
| [YouTube](https://www.youtube.com/channel/UC9wISUVH8DNyb1AK10i21vQ) | @wixo, ? | ?
| [Twitch](https://www.twitch.tv/lima_js) | @xpktro | ?
| [Facebook](https://www.facebook.com/groups/jsperu/) | ? | ?

**Comment by lizzie136** [comment]
Hola @lupomontero , lo que sé, lo edito directamente en tu cuadro o lo republico con el update?

**Comment by lupomontero** [comment]
> republico con el update?

:+1:

**Comment by wixo** [comment]
| Servicio | Admins | Tipo de cuenta
| --- | --- | ---
| [GitHub](https://github.com/lima-js) | @lizzie136, @wixo, @lupomontero, @jpscaletti, @PuercoPop  | org
| [AWS](https://aws.amazon.com/): dominio ([limajs.org](https://limajs.org/)) | @lupomontero | usuario personal
| [Cloudflare](https://www.cloudflare.com/): DNS | @lupomontero | usuario personal
| [Twitter](https://twitter.com/js_peru) | @lizzie136, @lupomontero, ? | usuario compartido
| [Slack](https://limajs.slack.com/) | @wixo | ?
| [Eventbrite](https://www.eventbrite.com/o/limajs-7913150001) | @wixo | se pueden asignar admins
| [YouTube](https://www.youtube.com/channel/UC9wISUVH8DNyb1AK10i21vQ) | @wixo | usuario personal
| [Twitch](https://www.twitch.tv/lima_js) | @xpktro | ?

Hasta ahora no conozco un grupo de Facebook q sea asociado a LimaJS.

**Comment by lupomontero** [comment]
Gracias @wixo.

He agregado a @Xpktro a la org en GitHub.

**Comment by lizzie136** [comment]
Servicio | Admins | Tipo de cuenta
-- | -- | --
GitHub | @lizzie136, @wixo, @lupomontero, @jpscaletti, @PuercoPop, @Xpktro  | org
AWS: dominio (limajs.org) | @lupomontero | usuario personal
Cloudflare: DNS | @lupomontero | usuario personal
Twitter | @lizzie136, @lupomontero, ? | usuario compartido
Slack | @wixo | ?
Eventbrite | @wixo, @lizzie136 | se pueden asignar admins
YouTube | @wixo | usuario personal
Twitch | @Xpktro

**Comment by lizzie136** [comment]
Servicio | Admins | Tipo de cuenta
-- | -- | --
GitHub | @lizzie136, @wixo, @lupomontero, @jpscaletti, @PuercoPop, @Xpktro  | org
AWS: dominio (limajs.org) | @lupomontero | usuario personal
Cloudflare: DNS | @lupomontero | usuario personal
Twitter | @lizzie136, @lupomontero, ? | usuario compartido
Slack | @wixo | ?
Eventbrite | @wixo, @lizzie136 | se pueden asignar admins
YouTube | @wixo | usuario personal
Twitch | @Xpktro 
Facebook | @Xpktro , @lupomontero ,  @lizzie136 | se puede asignar admins. Página. 
MeetUp | @lupomontero , CO @Xpktro @lizzie136 | PRO (Lupo), se puede asignar admins.

**Comment by lupomontero** [comment]
Cierro este issue por inactividad...
