### ISSUE TITLE
Liderazgo de la comunidad

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#21]
Hola todxs,

Me tomo la libertad de abrir este issue para "proponer" abiertamente formalizar un poco la "organización" de LimaJS.

Los objetivos principales detrás de esta propuesta son:

* Crecer la comunidad con una dirección clara
* Poder "representar" a la comunidad frente a otras comunidades, hacer alianzas, ...
* Poder formalizar auspicios/patrocinios
* Pensar en organizar / participar de eventos más grandes

En los últimos meses la organización de los meetups y administración de recursos de la comunidad a caido principalmente sobre los hombros de @lizzie136, @wixo, @xpktro y yo. Mi propuesta es presentarnos nosotros 4 como "organizadores oficiales". Estos "puestos" irían cambiando según vaya evolucionando la comunidad, pero la idea es que en todo momento hayan por lo menos 3 organizadores oficiales que puedan hacerse cargo de organizar los meetups y dar la cara por la comunidad.

Qué opinan? Qué proponen?

**Comment by Xpktro** [comment]
A favor de definir una pequeña estructura de representación para la comunidad, pues con esta se podrían hacer varias cositas como las que mencionas.

¿De qué manera se tendría que formalizar? Bastaría -por el momento, imagino- simplemente nombrar a la organización y empezar una hojita de ruta con responsabilidades repartidas, amirite?

**Comment by lupomontero** [comment]
Quizás por el momento podríamos cerrar esto con [este cambio](https://github.com/lima-js/limajs.org/pull/45/files#diff-04c6e90faac2675aa89e2176d2eec7d8R44)?

**Comment by talueses** [comment]
Muy entrometido yo por acá... Me gustaría agregar que; se definieran roles específicos. Ejemplo; "Perosnal de logística y protocolo", "Orador", etc...

**Comment by lizzie136** [comment]
@talueses , gracias por el aporte. Suena bien. El detalle para este caso es que varia dependiendo de algunas como el evento y disponibilidad. Creo que podemos verlo en la reunion previa a cada meet up.
