### ISSUE TITLE
Sistema de diseño con postCSS [Octubre - 2018]

### ISSUE THREAD

**Issue by techfano** [lima-js/limajs.org#25]
## ¿Qué tipo de presentación quieres hacer?
- Keynote (20 a 30 minutos) puede que hasta 45 mins maximo

## ¿Cuál es tu nombre?
Estefano

## ¿Cuál es el título de tu charla?
Guía de estilos y recursos para componentes con PostCSS

## Descripción de la charla

Primero, contare una breve historia de como se manejaban los estilos en CSS. Segundo, comparare formas de trabajo y organización de las clases y estilos en CSS. finalmente expondré y desarrollare código con ejemplos simples para mostrar como organizar estilos, preparar componentes usando semántica y respetando el estándar estructural de HTML.

## ¿Tienes alguna red social donde podamos contactarte?
https://www.facebook.com/techfano
https://twitter.com/techfano

## ¿Qué tipo de conector tiene tu laptop?
- [ ] HDMI mini

## ¿Quieres agregar algo más?
Ejemplo de mi trabajo a exponer
https://github.com/techfano/morph
Web de referencia del trabajo a exponer
https://morph.pe/

**Comment by lupomontero** [comment]
Gracias por la propuesta @techfano! Queda pre-agendada para Octubre. Cuando se acerque la fecha confirmamos los detalles (después del meetup de Sept).

cc/ @lizzie136 @wixo @Xpktro

**Comment by techfano** [comment]
De nada @lupomontero es un gusto compartir y apoyar siempre. Estamos coordinando en Octubre

**Comment by lupomontero** [comment]
Gracias por la charla @techfano :muscle: 

Cierro este issue ya que la charla ya se dio hoy :stuck_out_tongue:
