### ISSUE TITLE
Change Log - Agosto 2018

### ISSUE THREAD

**Issue by lizzie136** [lima-js/limajs.org#27]
### Participantes
@wixo , @lupomontero ,  @lizzie136. ( Nos faltó @Xpktro )
### Action Items && Conclusiones
- Hay decisiones que tomamos entre todos los organizadores (si afectan a la comunidad a largo plazo o en su crecimiento) y otras que podemos tomar entre al menos dos, cual peer review (cosas del día al día)
- Crear un issue que los compartamos al final del meet up y la gente nos pueda dar feedback ahí.
- Compartir las conclusiones y action items de nuestras retrospectivas (Change.log).
- El esfuerzo, objetivo que tenemos a mediano plazo sería llegar a 60 participantes promedio en el meet up, para ello, algunas acciones:
     - [X] Pasarnos meetUp.com, @lupomontero pondrá los primeros 6 meses para probar y se repondrá en cuanto se tenga sponsors para esta parte.
     - [X] Preguntarles a la comunidad qué cosa quiere o le interesa ver como tema.
     - [X] Crear una página en Facebook e Instagram como a nivel de comunidad, y luego 
     - [x] Decidir si publicamos contenido y ver una manera de automatizar el contenido. Ser los que somos.
- Que las personas y organizaciones puedan apoyar, sponsorear de diferentes maneras, para tener mejores bocaditos, más opciones de venue, entre otros.

### Organización del próximo meet up:

-   **Lugar**: 20 de Setiembre en **Laboratoria**.
 -  **Charlas**:
      - Andrea Carretero (UX for developers), @lizzie136 le haría seguimiento
      - @ManuelaFlores Manuela Flores (Android), @lupomontero  le haría seguimiento
      - @developerVilchez Lulú, @lupomontero  le haría seguimiento.
 -   **Eventbrite**: , estrenar meet up
 -   **PPTKaraoke**: Juan
 -   **Bocaditos**:  TBD

**Comment by lizzie136** [comment]
Hola a todos 👋 , para preguntarle a la comunidad, osea, todxs nosotrxs, se agregó esta encuesta:
https://goo.gl/forms/un23lXYNU6dYXQwV2
Si la pueden llenar sería genial! :D

**Comment by lupomontero** [comment]
Cerramos este issue por ahora (accionables completados) y continúa la conversación en https://github.com/lima-js/limajs.org/issues/40
