### ISSUE TITLE
Vue CLI 3 y Vue UI - "Home Run de Vuejs" (Noviembre 2018)

### ISSUE THREAD

**Issue by JoshDev1205** [lima-js/limajs.org#33]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Josh Ospina Tafur <Josh Dev>

## ¿Cuál es el título de tu charla?
Vue CLI 3 y Vue UI - "Home Run de Vuejs"

## Danos una descripción de tu charla (20 palabras)
Hablaré sobre los nuevos Workflow que nos trae VueJS y que nos permiten ser mucho mas agiles para controlar y gestionar nuestros desarrollos.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: https://twitter.com/Josh_Dev1205
Github: https://github.com/JoshDev1205/

## ¿Representas a alguna compañía o empresa?
Nirex Perú
## ¿Qué tipo de conector tiene tu laptop?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Gracias por la oportunidad de poder compartir conocimiento.
-----------
> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Gracias por la propuesta @JoshDev1205 !!

**Comment by JoshDev1205** [comment]
Lo paso para noviembre vale :smile:

**Comment by lizzie136** [comment]
:O! seguro @JoshDev1205 ? oki 👍

**Comment by lupomontero** [comment]
Gracias @JoshDev1205, esta charla queda agendada para el meetup de Noviembre! Gracias!

**Comment by JoshDev1205** [comment]
Cierro el Issue por el PR [#47](https://github.com/lima-js/limajs.org/pull/47)
