### ISSUE TITLE
Síntesis sustractiva para el resto de nosotros [Noviembre 2018]

### ISSUE THREAD

**Issue by Xpktro** [lima-js/limajs.org#34]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
> puede que incluso un poquito más
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Moisés Cachay

## ¿Cuál es el título de tu charla?
Síntesis sustractiva para el resto de nosotros.

## Danos una descripción de tu charla (20 palabras)
Explicaré qué es un sintetizador, cómo hacer uno usando JS y por qué es importante para la vida.

## ¿Tienes alguna red social donde podamos contactarte?
http://moises.ninja

## ¿Representas a alguna compañía o empresa?
A LimaJS :)

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Di esta charla el año pasado pero el tema nunca deja de estar vigente y creo que merece la pena repetir para nuestros nuevos asistentes y el récord en video con el que ya contamos.

Llevaré mi equipo de audio y maquinitas con luces, sólo necesitaría un amplificador o parlantes en el local para que los asistentes tengan la mejor experiencia posible.

**Comment by lupomontero** [comment]
@Xpktro, esta charla queda agendada para el meetup de Noviembre! Gracias!

**Comment by lupomontero** [comment]
Cierro este issue ya que esta charla ya se agregó a la agenda en https://github.com/lima-js/limajs.org/pull/46 :wink:
