### ISSUE TITLE
Llega ya Octubre

### ISSUE THREAD

**Issue by AndreaCarretero** [lima-js/limajs.org#36]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [√ ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Andrea Carretero

## ¿Cuál es el título de tu charla?
¿Ux? ¿Que es qué? . "Ha llegado el momento  de hablar .."

## Danos una descripción de tu charla (20 palabras)
¿Qué significa Ux - ¿Qué ramas existen? .En estos minutos se tiene como objetivo resolver todas las dudas posibles a los que no tengan claro aún que significar ser Ux , una Ux Designer . Las características, sus habilidades y las ramas que uno puede especializarse. 
Pd:  Ojo, estoy aprendiendo y quisiera compartirles lo que estoy descubriendo de este mundo .

## ¿Tienes alguna red social donde podamos contactarte?

https://www.linkedin.com/in/andrea-carretero-aa168016b/ 

## ¿Representas a alguna compañía o empresa?
Embajadora de Laboratoria 
## ¿Qué tipo de conector tiene tu laptop?

- [√ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Este es el comienzo de un reto,un gran reto y no seré la experta pero me encanta  lo que hago cada día así que nos vemos pronto :) - 
-----------
> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Gracias por la propuesta @AndreaCarretero !!!

**Comment by lizzie136** [comment]
Hola @AndreaCarretero , tu charla quedaría para nuestro meet up de este 18 de Octubre. Mandaré tu PR más tarde :D

**Comment by AndreaCarretero** [comment]
Gracias ,gracias por la oportunidad !! -
El 18 de Octubre nos vemos :)
