### ISSUE TITLE
Change Log - Septiembre 2018 

### ISSUE THREAD

**Issue by lizzie136** [lima-js/limajs.org#40]
## Participantes

@wixo , @lupomontero , @lizzie136, @Xpktro 

## Action Items && Conclusiones

Acuerdo para el próximo meeting: 
### Streaming

- [x] Preguntar por micrófono inalámbrico
    - [ ] Conseguir uno a mediano plazo
- [ ] Propuesta de capturardora: https://www.linio.com.pe/p/capturadora-de-video-ezcap-263-1080p-hdmi-hd-video-streaming-facebook-youtube-entrada-microfono-oom3g2
- [X] Usar música para intermedios (@Xpktro )
- [ ] Preguntar por las presentaciones antes (fondo blanco o buen contraste)
- [x] Usar un hashtag del evento

### Asistentes

- [X] Sponsors y catering (pastipan)
https://www.plazavea.com.pe/gaseosa-seven-up-lata-355ml-paquete-6un/p
Bebidas (visto por Lizzie)
- [ ] ~Consultar mover las sillas y mesas / si no probar con asistentes~
- [X] Preguntar la biografía del speaker
- [X] Agregar en la presentación a sponsors
- [X] Considerar issues en vez de PRs
- [ ] Crear nuevo tier de sponsorship único por mes en Open Collective
- [x] Revisar gist de Open Collective y considerar enviar PR a limajs.org
- [x] 2 o 3 carteles con indicaciones de cómo llegar/subir

## Organización del próximo meet up:

- Lugar: 18 de Octubre en Laboratoria.
- Charlas:
  - Hablemos sobre Vue.js por Jin Kadaba (@talueses)
  - Guía de estilos y recursos para componentes con PostCSS por Estéfano Castañeda (@techfano)
  - ¿UX designer? ¿Qué es qué? Ha llegado el momento de hablar... (@AndreaCarretero)
- [X] PPTKaraoke: @wixo , @brujorge 
- [X] Bocaditos: @lizzie136

**Comment by lizzie136** [comment]
Holi :) @lupomontero @wixo @Xpktro 
Quisiera que me confirmen estos puntos: 
- 2 o 3 carteles con indicaciones de cómo llegar/subir
   Se pusieron los carteles? 

- Crear nuevo tier de sponsorship único por mes en Open Collective
   Eso lo puede crear solo un admin? 
- Revisar gist de Open Collective y considerar enviar PR a limajs.org
   Puedes poner el link del gits @lupomontero ?

**Comment by lupomontero** [comment]
1. Me temo que al final no imprimimos los carteles... yo estuve un buen rato en la puerta guiando a la gente que llegaba, ... pero esto es algo que todavía tenemos que mejorar :see_no_evil: 

2. Esto creo que lo podemos crear cualquiera de los organizadores (@wixo, @Xpktro, tú y yo). Puedes chequear? Si no pueden crearlo me avisas y lo hago yo, ok?

3. Esto es algo que tenemos pendiente... y de hecho ya tenemos respuesta de dos posibles sponsors :tada: (además de Laboratoria :wink:)

**Comment by talueses** [comment]
Como una _crítica constructiva_; sería bueno crear un "flujo" (guía?)para los ponentes. Por así decirlo... En mi caso, llegué súper perdido. Estuve dando vueltas por allí y no tenía digamos que seguridad de estar en el sitio indicado. En el edificio afuera no hay algún indicio de ser el sitio correcto. Se debería agregar un par de correcciones a la dirección en la web de meetUp. Por ejemplo: 629A. 
Esto con respecto a la dirección, pero como mencioné en otro issue #21, capaz se resuelve mucho más fácil: Teniendo a alguien de "protocolo". :)

**Comment by lizzie136** [comment]
Gracias @talueses , de hecho lo de señalizar es para poder apoyar a que lleguen sanos y salvos al lugar. Mas allá de los ponentes claro.

**Comment by lizzie136** [comment]
@lupomontero de lo que conversamos, voy a cotizar los carteles que te mencione (plastificados) y trataré que se los envién antes de NodeSchool incluso, hay que pensar que en NodeSchool también vamos a necesitar.  Coordino con uds para que llegue a algún lugar de Lima 😄

**Comment by talueses** [comment]
Genial. Sí, la idea es también contribuir para los asistentes externos. :)

**Comment by lizzie136** [comment]
Los pendientes se mueven a Octubre. 👍
