### ISSUE TITLE
Primeros pasos con WebAssembly y Rust

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#42]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Lupo Montero

## ¿Cuál es el título de tu charla?

Primeros pasos con WebAssembly y Rust

## Danos una descripción de tu charla (20 palabras)

Esta charla es una intro a WebAssembly (normalmente abreviado Wasm) dirigida a desarrolladorxs web. Veremos un poco de qué es WebAssembly y el potencial que presenta para el futuro de JS, seguido de ejemplos prácticos con Rust y Wasm en el navegador.

## ¿Tienes alguna red social donde podamos contactarte?

https://twitter.com/lupomontero
https://github.com/lupomontero

## ¿Representas a alguna compañía o empresa?

Trabajo en Laboratoria. Las opiniones son mías.

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

Esta charla ya la di en el meetup de Mozilla Perú de oct 2018 (hace 2 días), pero creo que podría ser de interés para la comunidad de JavaScript en general.

Por otro lado, la duración original de esta charla es aprox. 45-60min, incluyendo ejemplos prácticos y demo al final... :cold_sweat: 

Se agradece feedback.

**Comment by lizzie136** [comment]
Hola @lupomontero ! podríamos tener un `dry run` de esta presentación ? cc. @wixo @Xpktro  ?

**Comment by lupomontero** [comment]
Hola @lizzie136, claro! Hablemos por el Slack de LimaJS... :wink:
