### ISSUE TITLE
Cambio de fecha de meetup de noviembre

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#43]
En noviembre hay muchxs que estamos yendo a Medellín para el [JSConf Colombia](https://jsconf.co/), que cae los días 16 y 17 de noviembre. Nuestro [meetup mensual](https://www.meetup.com/LimaJS/events/254302056/) está agendado para el jueves 15 (3er jueves del mes, como siempre) :cold_sweat: 

Les parece si lo reagendamos para el siguiente jueves (22)?

**Comment by lizzie136** [comment]
De lo conversamos en Slack Jueves 22 sería la fecha :D 
Nos queda confirmar el venue, cc @Laborataria 
Lo voy actualizando en meet up

**Comment by lizzie136** [comment]
Confirmado el Venue :)
