### ISSUE TITLE
5 essential technologies to keep your JS apps sane and scalable

### ISSUE THREAD

**Issue by mrtnzlml** [lima-js/limajs.org#51]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Martin Zlámal

## ¿Cuál es el título de tu charla?

5 essential technologies to keep your JS apps sane and scalable

## Danos una descripción de tu charla (20 palabras)

Keeping your JavaScript applications sane and scalable is very challenging and there are no silver-bullet tools for it. Well, actually… I am going to show you how I do it in Kiwi.com and my other projects. Get ready for 5 carefully cherry-picked tools and libraries I consider to be the key players in this heroic task. All in combination with practical tricks, tips, and recommendations from our experiences.

## ¿Tienes alguna red social donde podamos contactarte?

https://github.com/mrtnzlml

## ¿Representas a alguna compañía o empresa?

Yes, I work for Kiwi.com so I can share my experiences from the real, large-scale product.

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

I don't speak Spanish very well so I have to use English... 🙂🇬🇧

-----------
> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Thanks, @mrtnzlml! Nice topic! We will let you know if it fits in our meet up. How long are you going to stay in Lima?

**Comment by mrtnzlml** [comment]
Hi @lizzie136, I am going to be in Lima [from 30 Nov to 28 Dec](https://nomadlist.com/@mrtnzlml) (with some traveling around). Purpose of my trip to Peru is only traveling but I think it would be fun to do something like this since I do it even in Europe... :)

**Comment by lizzie136** [comment]
Hi again @mrtnzlml! Just wondering if we could have a [`dry run`](https://github.com/lima-js/limajs.org/issues/44) of your presentation. It could be remote, on a hangout or zoom. Can you set up a date and hour for it? If you want to chat about it, you can join our slack at https://holalimajs.herokuapp.com

**Comment by mrtnzlml** [comment]
@lizzie136 Yes, that sounds like a good idea. I am leaving _Prague_ to _Lima_ tomorrow so I could maybe do it in-person. I am going to contact you via Slack to discuss the details. 👋

**Comment by lupomontero** [comment]
Hi all,

I'm closing this issue as this talk has now been scheduled for saturday's event :tada: :+1: 

https://www.meetup.com/LimaJS/events/fqzsdqyxqbbc/
