### ISSUE TITLE
Graphql Stack - "Yoga + Prisma" (Abril 2019)

### ISSUE THREAD

**Issue by JoshDev1205** [lima-js/limajs.org#52]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Josh Ospina Tafur

## ¿Cuál es el título de tu charla?
Graphql Stack - "Yoga + Prisma"

## Danos una descripción de tu charla (20 palabras)
Hablaremos un poco de que es Graphql y como empezar a construir una API Full utilizando Yoga y Prisma

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: https://twitter.com/Josh_Dev1205
Github: https://github.com/JoshDev1205/

## ¿Qué tipo de conector tiene tu laptop?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias!
> El equipo de LimaJS

**Comment by JoshDev1205** [comment]
Recordatorio y Compromiso :smile:

**Comment by JoshDev1205** [comment]
@joshdev1205 estoy ansioso por la charla 😀

**Comment by lizzie136** [comment]
Hola @JoshDev1205! Tu charla ha sido seleccionada para el meet up de Abril 🎉 !! Te escribo por slack para coordinar tu dry run 😄 

cc. @lupomontero @wixo @Xpktro

**Comment by JoshDev1205** [comment]
Excelente :smile:

**Comment by lupomontero** [comment]
Esta charla ya está agendada para el jueves :star: ... así que cierro este issue :wink: 

Acá pueden ver la agenda "live" :earth_americas: 

https://limajs.org/
