### ISSUE TITLE
Experiencias de integración Javascript con servicios del Estado Peruano

### ISSUE THREAD

**Issue by marigobpe** [lima-js/limajs.org#53]
¿Qué vamos a presentar en LimaJS?

Experiencias de integración Javascript con servicios del Estado Peruano

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

Agenda: (diapositivas) (21 minutos)
Introducción a Gob.pe: innovando en el Estado Peruano 
(Diego Lume) 7min
Migrando el buscador de Gob.pe a React.JS
(José Chavez) 7min
Perfil de proveedores con Angular
(Fiorella Quino) 7min

## ¿Cuál es tu nombre?
Mari Giampietri

## ¿Cuál es el título de tu charla?
Experiencias de integración Javascript con servicios del Estado Peruano

## Danos una descripción de tu charla (20 palabras)
El equipo de Gob.pe busca siempre las mejores herramientas Javascript para mejorar la experiencia del ciudadano. Por ejemplo, utilizamos React para mejorar la experiencia de búsquedas en Gob.pe y Angular como SPA (Single Page Aplication) para buscar  proveedores del Estado.

## ¿Tienes alguna red social donde podamos contactarte?
www.gob.pe
https://medium.com/gob-pe

## ¿Representas a alguna compañía o empresa?
PCM (Presidencia del Consejo de Ministros)

## ¿Qué tipo de conector tiene tu laptop?
Llevaremos la presentación en memoria USB y en un link de Google Slides 
- [ X ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Llevaremos la presentación en Google Slides y en memoria USB.

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que la agenda ya está confirmada y contaremos con esta charla :tada: :rocket: 

https://www.meetup.com/LimaJS/events/fqzsdqyxqbbc/
