### ISSUE TITLE
Gestionando paquetes: dependencias confiables (Febrero 2019)

### ISSUE THREAD

**Issue by faurehu** [lima-js/limajs.org#55]
## ¿Qué tipo de presentación quieres hacer?

Keynote

## ¿Cuál es tu nombre?

Faure

## ¿Cuál es el título de tu charla?

Gestionando paquetes: dependencias confiables 

## Danos una descripción de tu charla (20 palabras)

Hablaremos sobre la necesidad de gestionar nuestros paquetes, compararemos NPM con Yarn, explicaremos como publicar paquetes en cualquiera de estos gestores. Y le echaremos chispitas ✨  de anécdotas del mundo de gestión de paquetes.

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @faurehu

## ¿Representas a alguna compañía o empresa?

No

## ¿Qué tipo de conector tiene tu laptop?

Mini DisplayPort

## ¿Quieres agregar algo más?

No soy un experto de por si en el tema pero estaré investigando sobre el tema en los próximos días y apunto a tener algo concreto para compartir :-)

**Comment by lizzie136** [comment]
¿Qué tal @faurehu? ¿Cómo te va con esta charla?

**Comment by faurehu** [comment]
Hola @lizzie136. Tengo un esqueleto pero me falta darle carne. Cuando te gustaría hacer el dry run?
