### ISSUE TITLE
Propuesta de charla: Reduce, reuse, recycle

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#57]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Lupo Montero

## ¿Cuál es el título de tu charla?

**Reduce, reuse, recycle**

## Danos una descripción de tu charla (20 palabras)

El concepto de _reducir_ un arreglo o transformarlo a otro valor es una abstracción super útil y versátil, pero puede ser un poco confuso de _visualizar_ al principio. En esta charla implementaremos nuestra propia función `reduce()` para ver la mecánica de cómo funciona, y despúes la usaremos para implementar `map`, `filter`, `forEach`, `join`, `includes`, `indexOf`, `lastIndexOf`, `reverse`, ... y todo esto en estilo funcional.

Esta charla esta inspirada en algunas preguntas de entrevistas de trabajo que han tenido algunas egresadas de Laboratoria. En particular la pregunta: _Implementa map, filter y forEach usando reduce_.

## ¿Tienes alguna red social donde podamos contactarte?

* [Twitter](https://twitter.com/lupomontero)
* [GitHub](https://github.com/lupomontero)

## ¿Representas a alguna compañía o empresa?

Trabajo en [Laboratoria](https://www.laboratoria.la/), las opiniones son mías.

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

**Comment by lizzie136** [comment]
Gracias por la propuesta @lupomontero !
