### ISSUE TITLE
Propuesta de charla: Árboles por todas partes

### ISSUE THREAD

**Issue by alejandrogarciasalas** [lima-js/limajs.org#61]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Alejandro García Salas

## ¿Cuál es el título de tu charla?

Árboles por todas partes: cómo librerias populares de JavaScript hacen uso de los ASTs

## Danos una descripción de tu charla (20 palabras)

Herramientas populares de JavaScript como Babel, ESLint, y JSCodeShift hacen uso de los ASTs (Abstract Syntax Trees) pero para muchas personas es un misterio como funcionan. La charla consistirá en una breve explicación de que son los ASTs, para que sirven y como es que herramientas como Babel, ESLint y JSCodeShift los utilizan. Después dare un breve demo (dependiendo del tiempo) de como usar ASTs con Babel, ESLint y JSCodeShift.

## ¿Tienes alguna red social donde podamos contactarte?

[Twitter](https://twitter.com/findAlejandro)
[GitHub](https://github.com/alejandrogarciasalas)

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

**Comment by lizzie136** [comment]
Hola @alejandrogarciasalas!!! Gracias por tu propuesta de charla, te parece si coordinamos en slack para tener un `dry run`? Básicamente es como un pequeño rehersal de tu charla con algunos de lxs organizadorxs para ver si hay algún tema técnico que tener en cuenta para tu charla y darte feedback 😄 
Conversamos!

**Comment by alejandrogarciasalas** [comment]
Hola @lizzie136 si claro, coordinamos por slack 👍

**Comment by lupomontero** [comment]
Esta charla ya está confirmada para el meetup del jueves (ver #63), así que me tomo la libertad de ir cerrando ese issue.

Gracias!
