### ISSUE TITLE
Talk proposal: Make your own MobX-like state management library in 40 lines of JS

### ISSUE THREAD

**Issue by michalczaplinski** [lima-js/limajs.org#62]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?

Michal Czaplinski

## ¿Cuál es el título de tu charla?

Make your own MobX-like reactive state management library!

## Danos una descripción de tu charla (20 palabras)

How to make your own (naive) state management library in less than 40 lines of JS! In the talk I will try to show some of the principles behind state management libraries like MobX. Live code demo included! 🙂

## ¿Tienes alguna red social donde podamos contactarte?

[github](https://github.com/michalczaplinski/)
[twitter](https://twitter.com/C_Z_A_P_L_A)

## ¿Representas a alguna compañía o empresa?
- just myself! I'm a freelancer :)

## ¿Qué tipo de conector tiene tu laptop?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
If the talk is accepted, would love to get a chance to practice it in front of someone IRL. I ll buy you coffee! 😄

**Comment by michalczaplinski** [comment]
@lizzie136 Hey! Are you guys considering the proposal for the upcoming meetup on 17th Jan? Can you give me a heads up as soon as you can so that I can work on some slides before Thursday? 
Cheers :)

**Comment by lupomontero** [comment]
Hi @michalczaplinski, thanks for the proposal :rocket: :star2: 

How long are you staying in Lima? Will you also be around in February?

**Comment by lupomontero** [comment]
In that case it would have to be our January meetup, which is this Thursday :wink: 

Could we schedule a _dry run_ via Hangouts or similar for tomorrow?

**Comment by michalczaplinski** [comment]
@lupomontero sure, that's great! I'd be happy to meet you in person someplace as well, if that works for you. Otherwise, either 6 or 7pm works for me tomorrow and let's coordinate on slack ? :)

**Comment by lupomontero** [comment]
Hi @michalczaplinski, see you tomorrow as scheduled :wink: 

I am closing this issue as the relevant PR has now been merged #63 

Many thanks!
