### ISSUE TITLE
Sugerencias y comentarios del público en NodeSchool Enero 2019

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#67]
Este issue recoge los comentarios y sugerencias del público en el [NodeSchool de enero 2019 en Laboratoria](https://www.meetup.com/LimaJS/events/257737029/).

Me he tomado la libertad de organizar la lista en _categorías_.

Los puntos a continuación se deben leer empezando cada uno con: _Sería chévere..._.

## General

- [ ] agregar una pregunta al hacer RSVP en meetup.com para entender los intereses de los asistentes

## NodeSchool

- [ ] saber más info sobre lxs mentorxs, sus especialidades, intereses, ...
- [ ] incluir algunas charlas e introducción a JavaScript y Node.js
- [ ] volver a hacer el _termómetro_ antes de arrancar con los _workshoppers_ para organizarnos en grupos más homogéneos

## Trivia

- [ ] tener _trivias_ con varios _niveles_ (aprendiz, intermedio, avanzado, ...)
- [ ] tener más retos de implementación, por equipos
- [ ] tener una mecánica más clara para los retos de implementación (GitHub, pruebas unitarias, HackerRank, ...)

## Charlas

- [ ] que cuando se confirmen charlas, incluyamos más info sobre temas y recursos relacionados (links a blog posts, videos, documentación, ...) para que lxs asistentes puedan tener más contexto.

**Comment by MaiaRojas** [comment]
Se podrian implementar las trivias con [kahoot.it](https://kahoot.it/)
