### ISSUE TITLE
Lazy component & Route on SPA

### ISSUE THREAD

**Issue by L4fv** [lima-js/limajs.org#70]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [*] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Luis Ángel flores Vallejos 

## Cuéntanos un poco sobre ti
Entrepreneur, JS FullStack Developer & Vue Advocate.
Actualmente laborando en el área de innovación de Acceso Corp, dando soluciones tecnológicas a los canales digitales.

## ¿Cuál es el título de tu charla?
Experiencia de usuario basado en componentes

## Danos una descripción de tu charla (20 palabras)
Carga asíncrona de componentes y rutas en aplicaciones SPA(Vue , React) para optimizar el primer render de la web

## ¿Tienes alguna red social donde podamos contactarte?
luanflov92@gmail.com, @luanflov twitter, https://fb.com/luanflov

## ¿Representas a alguna compañía o empresa?
Acceso corp

## ¿Qué tipo de conector tiene tu laptop?

- [* ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Hola @L4fv! Gracias por proponer una charla. ¿A que red social podríamos contactarte o correo?

**Comment by L4fv** [comment]
> Hola @L4fv! Gracias por proponer una charla. ¿A que red social podríamos contactarte o correo?

Listo. 👍

**Comment by mgmp2** [comment]
Qué tal @L4fv ! Estoy super interesada en tu charla

**Comment by lizzie136** [comment]
Hola @L4fv! estarías disponible para dar tu charla el 25 de Abril ?

**Comment by L4fv** [comment]
@lizzie136  genial. EL 25 me parece bien. Coordinamos 👍

**Comment by lizzie136** [comment]
Te escribo a tu correo para coordinar el dry run 
cc. @lupomontero @Xpktro @wixo

**Comment by lizzie136** [comment]
Hola @L4fv te escribí por correo, pero igual (puedes el martes para el dry run) 
El dry run es una presentación de tu charla con los organizadores, la idea es poder darte feedback sobre tu presentación a la vez que vemos detalles técnicos que puedas necesitar o que veamos que se requieran. 

¿Te parece si es el Martes después de la 5pm? 
¿Prefieres que sea online (videollamada) o presencial (en Laboratoria)?

**Comment by lupomontero** [comment]
Esta charla ya está agendada para el jueves :star: ... así que cierro este issue :wink: 

Acá pueden ver la agenda "live" :earth_americas: 

https://limajs.org/
