### ISSUE TITLE
Microservicios usando Nodejs

### ISSUE THREAD

**Issue by ldiego73** [lima-js/limajs.org#75]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Luis Fernando Diego Pinchi

## Cuéntanos un poco sobre ti
Arquitecto de Soluciones con más de 11 años como desarrollador y 3 como arquitecto, apasionado por las nuevas tecnologías. En mis tiempos libres soy Mochilero de corazón.

## ¿Cuál es el título de tu charla?
Microservicios usando Nodejs

## Danos una descripción de tu charla (20 palabras)
Microservicios + NodeJs una perfecta combinación.

## ¿Tienes alguna red social donde podamos contactarte?
https://www.facebook.com/ldiego73
https://www.instagram.com/ldiego73
https://www.linkedin.com/in/ldiego73

## ¿Representas a alguna compañía o empresa?
Belcorp

## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

Esto es el comienzo de una serie de charlas que pienso hablar sobre microservicios.

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Gracias por enviar la propuesta @ldiego73 :tada:

En los próximos días vamos a revisar las propuestas e iremos agendando las charlas. Te avisamos por acá, ok?

**Comment by JoshDev1205** [comment]
Uff que buena charla :+1:

**Comment by lizzie136** [comment]
Hola @ldiego73, estarás disponible para el 11 de mayo ? podemos conversar por algún medio ?

**Comment by ldiego73** [comment]
Hola que tal claro entiendo el sábado si estoy disponible, podemos coordinar por mi correo lfdiego7@gmail.com

**Comment by lupomontero** [comment]
Cierro este issue ya que la charla ya se dio en el meetup del pasado sábado :wink:
