### ISSUE TITLE
Sketch API powered by JS

### ISSUE THREAD

**Issue by erikfloresq** [lima-js/limajs.org#76]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Erik Flores

## Cuéntanos un poco sobre ti
Mobile Developer para TektonLabs

## ¿Cuál es el título de tu charla?
Sketch API powered by JS

## Danos una descripción de tu charla (20 palabras)
Mostrar las posibilidades que tiene el API de [Sketch 3](https://www.sketch.com/), la cual usa nodejs para crear plugins y publicarlas a su vez.

## ¿Tienes alguna red social donde podamos contactarte?
- twitter: @erikfloresq
- email: erikfloresq@gmail.com

## ¿Representas a alguna compañía o empresa?
TektonLabs

## ¿Qué tipo de conector tiene tu laptop?

- [ x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Hola @erikfloresq! Tu charla ha sido seleccionada para el meet up de Abril (25 de Abril). Te contactaré por slack para coordinar tu dry run 🎉

**Comment by lizzie136** [comment]
UPDATE: considerando que @erikfloresq no esta disponible esa fecha (Abril), su charla podría ser en otro mes :) 
cc @erikfloresq

**Comment by erikfloresq** [comment]
Muchas Gracias!

**Comment by lizzie136** [comment]
Hola @erikfloresq , hemos seleccionado tu charla para el meet up del **13 de Junio** 🎉, estás disponible para esa fecha? coordinemos por slack tu dry run :D

**Comment by erikfloresq** [comment]
Si :D

**Comment by JoshDev1205** [comment]
Thanks Erik :smile: 

It was awesome :+1:
