### ISSUE TITLE
Notificaciones ASAP usando Firebase 🔥☁️📲🔥

### ISSUE THREAD

**Issue by erikfloresq** [lima-js/limajs.org#77]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Erik Flores

## Cuéntanos un poco sobre ti

Mobile Developer en TektonLabs

## ¿Cuál es el título de tu charla?

Notificaciones ASAP usando Firebase 🔥☁️📲🔥

## Danos una descripción de tu charla (20 palabras)

Mostrar cómo enviar notificaciones usando desde la consola de Firebase hasta el SDK de 🔥Firebase🔥 para nodejs.

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @erikfloresq
Email: erikfloresq@gmail.com

## ¿Representas a alguna compañía o empresa?

TektonLabs

## ¿Qué tipo de conector tiene tu laptop?

- [x ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Gracias por la propuesta de charla @erikfloresq :rocket: :star: 

En los próximos días (o semanas :see_no_evil:) estaremos revisando todas las propuestas de charlas abiertas para ir agendándolas en los próximos meetups. Te avisamos por acá :wink:

**Comment by erikfloresq** [comment]
Muchas Gracias!

**Comment by lupomontero** [comment]
Hola @erikfloresq, acá haciendo un poco de _house keeping_ :house::broom: , ... me tomo la libertad de cerrar este issue ya que está inactivo desde hace más de 2 años :see_no_evil: 

Si la propuesta de charla sigue en pie avisanos y re-abrimos el issue. Por otro lado, simpre se pueden abrir issues para nuevas propuestas :wink:

**Comment by erikfloresq** [comment]
jajaj Perfecto!
