### ISSUE TITLE
En amores con async / await ❤️ 👩‍💻 

### ISSUE THREAD

**Issue by diananr** [lima-js/limajs.org#80]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?
- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
- Diana Navarro 

## Cuéntanos un poco sobre ti
- Hola! Soy desarrolladora front end en camino de ser full stack :)

## ¿Cuál es el título de tu charla?
- En amores con async / await ❤️ 👩‍💻 

## Danos una descripción de tu charla (20 palabras)
- Está dirigida a personas que hayan escrito código en js. El objetivo es hablar un poco de las promesas y como async / await nos facilita la vida 😃 

## ¿Tienes alguna red social donde podamos contactarte?
- Twitter: @diananr25
- Github: diananr
- Instagram: diananr25

## ¿Qué tipo de conector tiene tu laptop?
- [ ] HDMI
- [ ] Mini DisplayPort
- [x] VGA

## ¿Quieres agregar algo más?
- Muchas gracias! :)

---
> Muchas Gracias!
> El equipo de LimaJS

**Comment by wixo** [comment]
Hola @diananr, en LimaJS acostumbramos a tener una revisión previa de las presentaciones (dry run) como para dar feedback y tener una idea de que trata, cuándo podríamos tener esa llamada? cc: @lizzie136

**Comment by JoshDev1205** [comment]
Thanks @diananr 

It was amazing :+1: 

Closed :smile:
