### ISSUE TITLE
Estructuras de Gatos 😸

### ISSUE THREAD

**Issue by lizzie136** [lima-js/limajs.org#81]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Elizabeth Portilla

## Cuéntanos un poco sobre ti
Software Engineer, Head Coach en Laboratoria Ciudad de México. Me gusta leer, ver series, aprender cosas, en general. Comer.  Aprender de comida, comer más, y el espacio. 

## ¿Cuál es el título de tu charla?
Estructuras de Gatos

## Danos una descripción de tu charla (20 palabras)
Algunas implementaciones de estructuras de datos en JavaScript, interpretadas por gatos. 

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/lizita136
https://github.com/lizzie136

## ¿Representas a alguna compañía o empresa?
Lima JS / Laboratoria
## ¿Qué tipo de conector tiene tu laptop?

- [x] HDMI
- [x] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by JoshDev1205** [comment]
It was amazing :+1: 

Closed :smile:
