### ISSUE TITLE
Googlesheet as Database in nodejs and firebase

### ISSUE THREAD

**Issue by giancorzo** [lima-js/limajs.org#84]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Giancarlo Corzo

## Cuéntanos un poco sobre ti
Dev desde el siglo pasado, me gusta JS y Ruby. Me encanta diseñar productos nuevos asi no me hagan millonario. Soy lead architect en Tektonlabs donde desarrollo la arquitectura para múltiples proyectos en USA y Perú.

## ¿Cuál es el título de tu charla?
Googlesheet as Database in nodejs and firebase

## Danos una descripción de tu charla (20 palabras)
Como crear un API en Firebase que GoogleSpreadsheet como fuente de dato tanto para grabar como para leer.

## ¿Tienes alguna red social donde podamos contactarte?
https://github.com/giancorzo

## ¿Representas a alguna compañía o empresa?
Tektonlabs

## ¿Qué tipo de conector tiene tu laptop?

- [ X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
XOXO
---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lupomontero** [comment]
Gracias por la propuesta de charla @giancorzo :rocket: :star: 

En los próximos días (o semanas :see_no_evil:) estaremos revisando todas las propuestas de charlas abiertas para ir agendándolas en los próximos meetups. Te avisamos por acá :wink:

**Comment by lizzie136** [comment]
Hola @giancorzo  !! Tu charla ha sido seleccionada para el meet up de Julio 🎉 !! Por qué medio prefieres que te contacte para ver algunos detalles de tu charla?

**Comment by giancorzo** [comment]
Hola @lizzie136 

Me puedes contactar a mi correo personal gian.corzo@gmail.com

**Comment by lupomontero** [comment]
Hola @giancorzo, acá haciendo un poco de _house keeping_ :house::broom: , ... me tomo la libertad de cerrar este issue ya que está inactivo desde hace 2 años :see_no_evil: 

Si la propuesta de charla sigue en pie avisanos y re-abrimos el issue. Por otro lado, simpre se pueden abrir issues para nuevas propuestas :wink:
