### ISSUE TITLE
VIM: edición eficiente de texto

### ISSUE THREAD

**Issue by faurehu** [lima-js/limajs.org#85]
## ¿Qué tipo de presentación quieres hacer?

- Keynote de 30 minutos

## ¿Cuál es tu nombre?

Faure Hu

## Cuéntanos un poco sobre ti

Soy un programador que jura por sus herramientas. VIM es una herramienta central en mi trabajo y estoy ilusionado por contar cómo me ha cambiado la vida y compartir recursos para que cada uno pueda empezar su camino con VIM.

## ¿Cuál es el título de tu charla?

VIM: edición eficiente de texto

## Danos una descripción de tu charla (20 palabras)

Con VIM trabajas menos para lograr lo mismo. Deja de copiar y pegar variables en tu codigo y descubre cómo multiplicar tu esfuerzo.

## ¿Tienes alguna red social donde podamos contactarte?

twitter.com/hu_am__i

## ¿Representas a alguna compañía o empresa?

No

## ¿Qué tipo de conector tiene tu laptop?

HDMI

## ¿Quieres agregar algo más?

Esto sigue siendo relevante a Javascript pero también es una propuesta atractiva para cualquier tipo de persona que trabaje con texto (programadores, analistas, escritores, etc).

**Comment by lupomontero** [comment]
Gracias por la propuesta de charla @faurehu :rocket: :star: 

En los próximos días (o semanas :see_no_evil:) estaremos revisando todas las propuestas de charlas abiertas para ir agendándolas en los próximos meetups. Te avisamos por acá :wink:

**Comment by lizzie136** [comment]
Hola @faurehu !! Tu charla ha sido seleccionada para el meet up de Julio 🎉 !! Te contactaré por slack para ver los detalles.
