### ISSUE TITLE
Propuesta de charla: Combinando y grabando video y audio en el navegador

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#86]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Lupo Montero

## Cuéntanos un poco sobre ti

Director de Tecnología y Head JavaScript Coach en @Laboratoria.  Co-organizador de @lima-js. Voluntario en @mozillaperu.

## ¿Cuál es el título de tu charla?

Combinando y grabando ⏺ video 🎥 y audio 🎙 en el navegador

## Danos una descripción de tu charla (20 palabras)

En esta charla veremos cómo, con APIs nativas del navegador, podemos acceder a streams de video (cámara, pantalla, ventana, ...) y audio (micro) con [`MediaDevices`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices), combinarlos usando [`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream), componer imágenes en un [`canvas`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement), y grabar el resultado en un archivo de video usando [`MediaRecorder`](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder).

Disclaimer: Esta es una charla que ya presenté en un meetup reciente de Mozilla Perú, pero creo que podría interesar también a la comunidad de LimaJS :wink: 

## ¿Tienes alguna red social donde podamos contactarte?

* https://twitter.com/lupomontero

## ¿Representas a alguna compañía o empresa?

@Laboratoria, @lima-js, @mozillaperu.

**Comment by joelibaceta** [comment]
@lupomontero esta charla me parece interesante, hice algo similar hace algunos meses para hacer streaming de un editor de código en linea, hay muchas cosas interesantes +1 a retomar esta charla para futuros meetups 👍
