### ISSUE TITLE
Propuesta de charla: React explicado con Vanilla JS

### ISSUE THREAD

**Issue by ivandevp** [lima-js/limajs.org#90]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Iván Medina

## Cuéntanos un poco sobre ti

JavaScript Engineer @zipdev. Previously @Laboratoria. OSS enthusiast. @reactjs practitioner. @rustlang apprentice.

## ¿Cuál es el título de tu charla?

React explicado con Vanilla JS

## Danos una descripción de tu charla (20 palabras)

El objetivo de esta charla es aprender los principios de React a través de la construcción de una versión mínima de React y abstracciones más usadas de su API.

## ¿Tienes alguna red social donde podamos contactarte?

* [https://twitter.com/ivandevp](https://twitter.com/ivandevp)

## ¿Representas a alguna compañía o empresa?

@zipdev, @Laboratoria

**Comment by lupomontero** [comment]
Buenazo! Si no me equivoco @lizzie136 está coordinando la agenda y _dry runs_, y te escribirá esta tarde para coordinar.

**Comment by lizzie136** [comment]
Coordinado, les envío el invite :)

**Comment by JoshDev1205** [comment]
Thanks Ivan :smile: 

It was awesome :+1:
