### ISSUE TITLE
Directorio de comunidades de JavaScript en Perú

### ISSUE THREAD

**Issue by lupomontero** [lima-js/limajs.org#91]
Sería muy chévere hacer algo como [coljs.org](http://www.coljs.org) bajo el paraguas de @peru-dev... :thinking: ... como referencia yo tengo el dominio javascript.pe y podríamos usarlo para alojar esto.

Ver:

* https://github.com/peru-dev/peru-dev.org/pull/2#issuecomment-498811909
* https://github.com/peru-dev/peru-dev.org/issues/1

**Comment by wixo** [comment]
Hola!, friendly reminder que JavaScript es un [_trademark_ de Oracle](http://tsdr.uspto.gov/#caseNumber=75026640&caseType=SERIAL_NO&searchType=statusSearch) (👎), es por eso que la mayoría de [comunidades usa JS](https://github.com/voodootikigod/logo.js/) para referirse a lo que todos conocemos como JavaScript(™). En un menor uso está EcmaScript.

Sería genial poder usar alguna alternativa que fomente el uso de JS o ES sobre JavaScript.

**Comment by lupomontero** [comment]
Gracias por el comentario @wixo :+1: 

Se agradecen ideas para dominios... algo como perujs.org sería ideal, pero ya está tomado... y porfa si saben de cualquier otra comunidad de JS en Perú compartan info por acá :wink:

**Comment by lizzie136** [comment]
Hola @lupomontero , esto no sería un paraguas sobre otro paraguas? Entendería que peru-dev puede ser una primera instancia más general y si vemos la necesidad de que se haga algo más específico ya podemos ir viendolo con la necesidad. Bueno, eso es lo que me parece.

**Comment by talueses** [comment]
Creo que pudiera ser un listado dentro del paragua. Algo como para "mapear" y hacer un poco más "fácil" el acceso o visibilidad a otras comunidades. 
Si se comienza la lista: 
0.- VueJs Lima.

**Comment by joelibaceta** [comment]
@lupomontero @lizzie136 escribo para comentar que con algunas personas de lima estamos trabajando en algo similar basado en los grupos de meetup de lima, por ahi les sirve como inspiración o quieren sumarse al proyecto.

Les dejo el repo: https://github.com/peruanosdev/peruanos.github.io
Y el sitio estático: http://peruanos.dev

Estamos haciendo algunas cosas interesante a nivel de código :) para mantener la simplicidad del proyecto.

**Comment by lupomontero** [comment]
Hola @joelibaceta :rocket: 

Justo me encontré con @07Gond hace un par de semanas en la NodeConf en Medellín y me contó un poco por encima sobre la iniciativa de @peruanosdev... y yo brevemente le conté sobre @peru-dev... creo que estamos apuntando en una misma dirección y me encantaría que pudiéramos sumar esfuerzos y colaborar :smiley: 

Como primer punto de contacto, he quedado en conversar el viernes con @07Gond para darnos más contexto y entender mejor a ambos lados. De ahí creo que sería muy chevere que pudiéramos conversar en un _foro_ común y colaborar bajo un mismo paraguas :umbrella:.

Veo que han [_forkeado_](https://github.com/peruanosdev/codigo-de-conducta) el código de conducta de @colombia-dev, [lo mismo que hicimos nosotrxs](https://github.com/peru-dev/codigo-de-conducta) :see_no_evil: 

Me encantaría invitarlxs a que echen un vistazo al [`README.md` donde estamos tratando de acordar una serie de valores y principios compartidos](https://github.com/peru-dev/peru-dev.org/blob/master/README.md), que consideramos los pilares de la iniciativa. Sería buenazo tener su opinión sobre eso y que exploren también los issues (especialmente los [etiquetados como `help-wanted`](https://github.com/peru-dev/peru-dev.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :wink:).

**Comment by joelibaceta** [comment]
@lupomontero genial, por lo pronto he estado aportando activamente precisamente por que vi que era un fork de colombia-dev el cual me parecía que era demasiado precario y podría mejorarse, ahi vamos trabajando en algunas ideas ( https://github.com/peruanosdev/peruanos.github.io/issues ).

Por lo pronto prefiero mantenme distante de la política interna, espero puedan alinearse con @07Gond en búsqueda de una sinergia, cuenten conmigo para los aportes técnicos.

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue en favor de colaborar directamente en https://github.com/peruanosdev/peruanos.github.io
