### ISSUE TITLE
Consulta: ¿La web actualmente tiene un bug? O.O

### ISSUE THREAD

**Issue by talueses** [lima-js/limajs.org#93]
Actualmente, ¿hay un cambio en el diseño/CSS en la web de limajs? Me parece que algo explotó... 
(A no ser que hayan cambiado el diseño...) 
CC: @lupomontero @wixo @lizzie136 

![Screenshot from 2019-06-05 16-43-14](https://user-images.githubusercontent.com/1497636/58992665-0e46e880-87b1-11e9-97b2-93fcf703c7b1.png)

**Comment by lizzie136** [comment]
jeje se ve como lo pensó @wixo 👀

**Comment by talueses** [comment]
De ser así entonces, cierro el issue.

**Comment by lizzie136** [comment]
👀 gracias por el feedback @talueses, creo que @wixo tenía pensado que fuera como el output de un terminal claro.
