### ISSUE TITLE
Node Conf Colombia: el poder de las comunidades.

### ISSUE THREAD

**Issue by Danielalab** [lima-js/limajs.org#95]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Daniela Gonzales
## Cuéntanos un poco sobre ti
Soy front end developer egresada de Laboratoria y actualmente coach de Js en Laboratoria. Amante de los gatos :heart_eyes_cat: y el hip hop :musical_note:

## ¿Cuál es el título de tu charla?
Node Conf Colombia: el poder de las comunidades.

## Danos una descripción de tu charla (20 palabras)
Compartir mi experiencia en la NodeConf e invitar a mas developers a participar en este tipo de conferencias.

## ¿Tienes alguna red social donde podamos contactarte?
Github: https://github.com/Danielalab

## ¿Representas a alguna compañía o empresa?
Laboratoria
## ¿Quieres agregar algo más?

---

:information_source: En los meetups normalmente usamos dos proyectores. Para
poder proyectar en ambos necesitarás:

1. [Google Chrome](https://www.google.com/chrome/) (para acceder a Chrome Cast)
1. [Apple Airplay](https://www.apple.com/airplay/) (usuarios de macOS no tienen
   que hacer nada) o alternativamente (Linux, Windows, ...) instalar
   [Airtame](https://airtame.com/download/).

Cualquier pregunta no duden en consultar a lxs organizadores :wave:

---

> Muchas Gracias!
> El equipo de LimaJS

**Comment by lizzie136** [comment]
Hola @Danielalab !! Tu charla ha sido seleccionada para el meet up de Julio 🎉 !! Te contactaré por slack para ver los detalles 💛 !!
