### ISSUE TITLE
Propuesta de charla: From zero to hero in 15 minutes

### ISSUE THREAD

**Issue by byteconde** [lima-js/limajs.org#98]
## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [X] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Deyvi Conde
## Cuéntanos un poco sobre ti
Aprendiz de Computer Science 💻 . Apasionado al emprendimiento social, la educación disruptiva y los modelos de sharing-economy.

## ¿Cuál es el título de tu charla?
Async await, promises and callbacks in 15 minutes, from zero to hero 😄. 
## Danos una descripción de tu charla (20 palabras)
¿Recuerdan los callbacks y luego las promesas? Pues ahora amarás y harás de async-await tu mejor amigo ❤️ . Realizaremos una pequeña demo usando callbacks, luego haremos el mismo ejemplo usando promesas y finalmente notaremos la diferencia y el gran ahorro de lógica usando async await.  

## ¿Tienes alguna red social donde podamos contactarte?

- Twitter: www.twitter.com/byteconde
- Mail: iamdeyvi@gmail.com

**Comment by lizzie136** [comment]
Hola @byteconde ! Te animas a dar esta charla en nuestro meetup el 25 de Julio?

**Comment by byteconde** [comment]
Cool @lizzie136 , desde luego que sí.

**Comment by lizzie136** [comment]
Te escribí por correo, coordinemos por ahí :)

**Comment by byteconde** [comment]
Lizzie, he revisado mi mail y no visualizo nada. ¿Me puedes enviar otro mail o indicarme el tuyo? Gracias 😄

**Comment by lizzie136** [comment]
@byteconde ! enviado, ahora si, 100% real, no fake :)
