### ISSUE TITLE
Talk proposal: TypeScript + React: the what, why and how.

### ISSUE THREAD

**Issue by michalczaplinski** [lima-js/limajs.org#99]
> Nuestros eventos se rigen por el siguiente [Código de conducta](http://es.confcodeofconduct.com/)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Michal Czaplinski

## Cuéntanos un poco sobre ti
I'm a freelance web engineer, working mostly with JS nowadays. I've been a "digital nomad" until recently, but I'm starting to call Peru my home!

## ¿Cuál es el título de tu charla?
TypeScript + React: The what, why and how.

## Danos una descripción de tu charla (20 palabras)
• What? What is Typescript really - a quick tour of the language.
• Why? Type safety and superior developer experience - I'm gonna show you some killer TS features.
• How? I ll outline how best to get started with TS and also how best to integrate it into an existing (react) project!

## ¿Tienes alguna red social donde podamos contactarte?
[github](https://github.com/michalczaplinski/)
[twitter](https://twitter.com/C_Z_A_P_L_A)

## ¿Representas a alguna compañía o empresa?
just myself :)

**Comment by lupomontero** [comment]
Cierro este issue ya que esta charla ya se dio en noviembre :wink:
